platform :ios, '8.0'
target 'OpenDingTalkHelperForiOS' do
	pod 'ZXTableView'
	pod 'ZXEmptyView'
	pod 'ZXDataHandle'
  pod 'ZXSlideSelectTableView'
  pod 'BRPickerView'
  pod 'Masonry'
  pod 'CRBoxInputView'
  pod 'TDTouchID'
  pod 'ZXNavigationBar'
end
